"""P-W0 (arc `tabs-compression-work`): run-twice-identical smoke gate for
``tools/quiet_room_drift.py``. Short prefix only (50 ticks) — the committed
2000-tick baseline capture lives in
``docs/tabs_compression_work_baseline_2026-08-20.md``, regenerated by hand,
not by this test.
"""
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
for _p in (ROOT, ROOT / "src", ROOT / "tools",
           ROOT / "cpp" / "build" / "Release"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import pytest

bp = pytest.importorskip("breach_physics")
import quiet_room_drift as qrd  # noqa: E402


def test_quiet_room_drift_is_run_twice_identical():
    a = qrd.run(ticks=50)
    b = qrd.run(ticks=50)
    assert a["summary"] == b["summary"]
    for k in a["series"]:
        assert np.array_equal(a["series"][k], b["series"][k]), (
            f"series {k!r} diverged across two runs of the same scenario")


def test_quiet_room_drift_t_is_almost_a_fixed_point_on_head():
    """HEAD is pre-T_abs-compression-work: step 4c is analytically exact-zero
    at T_rel=0 (both branches — ``mul_q16(k, 0)`` and
    ``floordiv_q(0<<16, ...)`` — collapse to 0 regardless of k, verified
    against ``eos_solver.cpp:1006-1018``). Measured on HEAD, though: a tiny
    +-1-raw-Q16.16-count transient (<= ~6e-5 game-deg) appears around the
    bump in ticks 1-3 and fully self-heals to exact 0 by tick 4 — this is
    the PRE-EXISTING, already-bounded P-E1 SL-transport LSB truncation noise
    (test_e1_hot_rail.py's test_no_transport_mint /
    test_transport_delta_is_one_way_negative govern it: the RUN TOTAL is a
    pure loss, but an individual active-flux cell can round either way), NOT
    a step-4c effect and NOT new to this arc. Recorded here so the T_abs
    baseline doc states the true measured value rather than an idealized
    zero."""
    out = qrd.run(ticks=50)
    s = out["summary"]
    assert s["max_abs_t_rel_over_run"] < 1e-3, (
        "T drift far exceeds the known SL-transport LSB noise ceiling — "
        "investigate before treating this as the P-E1 artifact")
    assert s["t_min_gas_over_run"] == 0.0, "no sub-ambient undershoot expected"
    assert s["eos_energy_books_sum_end"] == 0, (
        "the transient must fully self-heal within the run")
