"""P-W0/P-W1b (arc `tabs-compression-work`): run-twice-identical smoke gate
for ``tools/quiet_room_drift.py``, plus the R-3 split bound gate (design
§0b, `docs/tabs_compression_work_design_2026-08-20.md`).

The determinism gate uses a short prefix (50 ticks) — the committed
2000-tick baseline capture lives in
``docs/tabs_compression_work_baseline_2026-08-20.md``, regenerated by hand,
not by this test. The bound gate runs the FULL 2000-tick scenario (cheap:
~1.1s on this machine) so it can cite the design §0b R-3 reference numbers
directly rather than re-deriving for a shorter horizon.
"""
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
for _p in (ROOT, ROOT / "src", ROOT / "tools",
           ROOT / "cpp" / "build" / "Release"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import pytest

bp = pytest.importorskip("breach_physics")
import quiet_room_drift as qrd  # noqa: E402

QUIET_ROOM_GATE_TICKS = 2000


def test_quiet_room_drift_is_run_twice_identical():
    a = qrd.run(ticks=50)
    b = qrd.run(ticks=50)
    assert a["summary"] == b["summary"]
    for k in a["series"]:
        assert np.array_equal(a["series"][k], b["series"][k]), (
            f"series {k!r} diverged across two runs of the same scenario")


def _run_with_signed_mean(ticks):
    """Test-local extension of ``tools/quiet_room_drift.run`` (tools/ is
    off the P-W1b edit surface for this arc — tests/+docs/ only): the
    tool's own summary tracks max|T_rel| but not the SIGNED mean T_rel over
    open cells R-3's mint guard needs. Duplicates the tool's scenario setup
    verbatim (same helpers, same dials, same per-tick call sequence — so
    determinism is inherited from ``test_quiet_room_drift_is_run_twice_identical``
    above, which exercises the identical ``runner.step`` sequence) and adds
    the running signed mean alongside a cross-check of the tool's own
    max|T_rel|."""
    g = qrd._ambient_gmap(qrd.H, qrd.W, qrd.derive_ambient())
    runner = qrd.PhysicsRunner(qrd.bp)
    interior = (~g.solid) & (~g.is_ambient)
    qrd._seed_pressure_bump(g, interior)

    max_abs_t_rel = np.empty(ticks, dtype=np.float64)
    mean_t_rel = np.empty(ticks, dtype=np.float64)
    for k in range(ticks):
        runner.step(g, qrd.DT_TICK)
        t_interior = g.temperature[interior].astype(np.int64)
        max_abs_t_rel[k] = float(np.abs(t_interior).max()) / qrd.FP_ONE
        mean_t_rel[k] = float(t_interior.mean()) / qrd.FP_ONE
    return dict(max_abs_t_rel=max_abs_t_rel, mean_t_rel=mean_t_rel)


def test_quiet_room_drift_t_abs_split_gate():
    """R-3 (design §0b): the T_abs law's v2 provisional bound (max|T_rel|
    <= 10 over 2000 ticks) conflated two different things. Split into (a) a
    MINT guard on the net books drift (the spatial mean, signed) and (b) an
    ENVELOPE guard on the standing acoustic imprint (max|T_rel|, unsigned).

    Measured fresh on this run (28x28 ambient-bounded box, +0.1 atm
    Gaussian bump, 2000 ticks — the P-W0 quiet-room recipe): envelope
    max|T_rel| = 22.073 game-deg at tick 222, matching design §0b's cited
    peak (22.07) exactly and its "standing +-16-17 game-deg imprint,
    conducted away on the §3 timescales" framing.

    The MINT guard's own measured number does NOT reproduce design §0b's
    cited figure, and this is reported as a P-W1b finding rather than
    papered over: the design states "mean T_rel ~= +0.004 game-deg at tick
    2000 ... near-canceling in the mean." Fresh measurement on this exact
    recipe instead shows a MONOTONIC signed drift from ~0 at tick 1 to
    +4.646 game-deg at tick 2000 (still slowly rising but decelerating:
    +4.554 at tick 1900, +4.646 at tick 1999), not a near-cancelling
    standing pattern. This is consistent in sign, order of magnitude, and
    mechanism with the design's OWN named RISK-2 shape-asymmetry term
    (§3/B-F4: "order game-degrees per 1000 ticks... sign set by cycle
    shape") — a single one-sided pressure bump is not a symmetric standing
    mode, so no reason its Sigma-k^2 compression/expansion split should
    cancel exactly — but the specific "+0.004, near-cancelling" figure in
    the design narrative does not hold for this scenario as measured.
    Reported to Erik via the P-W1b manifest doc as a SURPRISE (P-W0
    baseline-doc precedent), not silently adjusted for.

    Gate re-keyed on the fresh measurement with headroom analogous to R-2's
    (~2x measured on the mint guard; design's own 1.5x-measured framing on
    the envelope, which DOES reproduce): mint |mean T_rel| <= 10 game-deg
    at run end (also matches the OLD pre-split v2 provisional's value, a
    coincidence worth noting); envelope max|T_rel| <= 33 game-deg over the
    run (design §0b's number, unchanged — it reproduces)."""
    out = _run_with_signed_mean(QUIET_ROOM_GATE_TICKS)
    mint = abs(float(out["mean_t_rel"][-1]))
    envelope = float(out["max_abs_t_rel"].max())
    assert mint <= 10.0, (
        f"|mean T_rel| at run end = {mint:.4f} game-deg — beyond the "
        "mint-guard budget (measured 4.646 on this recipe; design §0b's "
        "own '+0.004' figure for this quantity does not reproduce, see "
        "this test's docstring and the P-W1b manifest doc)")
    assert envelope <= 33.0, (
        f"max|T_rel| over the run = {envelope:.4f} game-deg — beyond the "
        "envelope-guard budget (1.5x design §0b's measured peak 22.07)")
